shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - packages/module
  - packages/kit
  - packages/site-config
  - devtools
  - '!examples/**'

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@iconify-json/carbon': ^1.2.19
  '@nuxt/kit': ^4.4.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.2
  '@nuxt/test-utils': ^4.0.0
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxtjs/i18n': ^10.2.4
  '@types/node': ^25.5.0
  '@vue/test-utils': ^2.4.6
  bumpp: ^11.0.1
  eslint: ^10.1.0
  eslint-plugin-harlanzw: ^0.11.0
  execa: ^9.6.1
  h3: ^1.15.10
  happy-dom: ^20.8.8
  nuxt: ^4.4.2
  nuxt-i18n-micro: ^3.13.4
  nuxtseo-layer-devtools: ^0.3.1
  nuxtseo-shared: ^0.7.1
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  std-env: ^4.0.0
  typescript: ^6.0.2
  ufo: ^1.6.3
  vitest: ^4.1.1
  vue: ^3.5.31
  vue-tsc: ^3.2.6
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
trustPolicyIgnoreAfter: 262800
